from .actividades import *
from .clase_ocurrir_sala import *
from .clases import *
from .descuentos import *
from .mensualidades import *
from .pago_pagar_clase import *
from .pago_pagar_mensualidad import *
from .pagos import *
from .permisos import *
from .profesores import *
from .rol_tener_permiso import *
from .roles import *
from .salas import *
from .usuario_cancelar_clase import *
from .usuario_inscribir_clase import *
from .usuario_tener_descuento import *
from .usuarios import *
from .construir_db import *
from .conectar_db import *
from .commitear_db import *
from .seed_db import *